### ISSUE TITLE
日志引用问题

### ISSUE THREAD

**Issue by yangs0123** [Nepxion/Matrix#2]
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.nepxion.matrix.aop.AbstractAutoScanProxy.<clinit>(AbstractAutoScanProxy.java:36)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1147)
	... 17 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more

**Comment by yangs0123** [comment]
日志组件换一下OK了

**Comment by Nepxion** [comment]
在外部引用，需要自己自行添加日志的maven引入，因为有些人喜欢log4j2，有些人喜欢用logback，在父工程里提供log4j2的引用，你可以参考一下

**Comment by yangs0123** [comment]
好的，谢谢解答。

**Comment by Nepxion** [comment]
不客气
