### ISSUE TITLE
运行报错啊

### ISSUE THREAD

**Issue by wzxit** [Nepxion/Matrix#8]
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextInitializer
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:268)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:249)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.nepxion.matrix.proxy.example.simple.Test.main(Test.java:9)
Caused by: java.lang.ClassNotFoundException: org.springframework.context.ApplicationContextInitializer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by HaojunRen** [comment]
我测试一下，不存在这个问题
